# .github/actions/action.yaml
name: "Local Checkout"
description: "A wrapper for the official checkout action to comply with local action policies."

# Define the inputs your action will accept. These will be passed to the underlying action.
inputs:
  ref:
    description: 'The branch, tag or SHA to checkout.'
    required: false
    default: ${{ github.ref }}
  token:
    description: 'GitHub token for checking out private repositories.'
    required: true
    default: ${{ secrets.GITHUB_TOKEN }}

# Define the execution steps for this composite action.
runs:
  using: "composite"
  steps:
    - name: Checkout Code
      # Here is where you use the official action.
      # The policy allows this because this 'uses' is inside a local action.
      uses: actions/checkout@v4 # Use a modern version
      with:
        # Pass the inputs from this action down to the real checkout action.
        ref: ${{ inputs.ref }}
        token: ${{ inputs.token }}