# .github/workflows/create-pages.yaml
# Build, Lint, and deploy
name: Build, Lint, and Deploy

on:
  # Runs on pushes and PRs targeting main
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows manual runs from the Actions UI
  workflow_dispatch:

# Sets permissions on GITHUB_TOKEN for the entire workflow.
permissions:
  contents: read
  pages: write
  id-token: write
  packages: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build and lint, producing a deployable artifact
  build:
    name: Build and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4                   # 1. Get the code to run

      - name: Set up node.js                        # 2. Set up the runtime environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'                              # npm's cache speeds up runtime on future builds

      - name: Install dependencies                  # 3. Install dependencies
        run: npm ci

      - name: Run HTMLHint                          # 4. Run the HTML linter
        run: npx htmlhint "**/*.html"

      - name: create new artifacts directory        # 5. create the artifacts directory for the build artifact
        run: |
          mkdir build
          mv index.html build/

      - name: Upload artifact                       # Now upload an artifact to GH Pages
        uses: actions/upload-pages-artifact@v3
        with:
          # Stick the artifact in the build directory
          path: './build'

  # Build and push a Docker image to the GitHub Container Registry
  build-docker:
    name: Build and Push Docker Image
    needs: build
    permissions:
      contents: read
      packages: write
    uses: jd-meyer/ci-cd/.github/workflows/build-docker.yaml@main

  # Deploy to the target environment by calling a reusable workflow
  deploy-reusable:
    name: Deploy via Reusable Workflow
    needs: build
    # Grant permissions to the reusable workflow
    permissions:
      pages: write
      id-token: write
    uses: jd-meyer/ci-cd/.github/workflows/deploy-pages.yaml@main

  # Download and list my artifact
  artifact:
    name: Verify Artifact
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download-artifact
        uses: actions/download-artifact@v4
        with:
          # required for Pages artifacts
          name: github-pages
      - name: List artifact contents
        run: ls -R
