# .github/workflows/create-pages.yaml
# Build, Lint, and deploy
name: SDLC-Main Orchestrator

on:
  # Runs on pushes and PRs targeting main
  push:
    branches: ["feature/**"]
  pull_request:
    branches: ["main", "test/**", "release/**"]
  # Allows manual runs from the Actions UI
  workflow_dispatch:

# Sets permissions on GITHUB_TOKEN for the entire workflow
permissions:
  contents: read
  pages: write
  id-token: write
  packages: write

# Allow only one concurrent deployment PER ENVIRONMENT
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # This job now calls a reusable workflow to build the application
  build-app:
    name: Build Application
    uses: jd-meyer/ci-cd/.github/workflows/build-application.yaml@main
    # No permissions are needed here because the reusable workflow defines its own permissions

  # Build and push a Docker image to the GitHub Container Registry
  build-docker:
    name: Build and Push Docker Image
    needs: build-app  # Depends on build application completion
    permissions:
      contents: read
      packages: write
    uses: jd-meyer/ci-cd/.github/workflows/build-docker.yaml@main

  # Deploy to the target environment by calling a reusable workflow
  deploy-to-dev:
    name: Deploy to Dev environment
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/feature/')
    needs: build-app  # Depends on build application completion
    # Grant permissions to the reusable workflow
    permissions:
      pages: write
      id-token: write
    uses: jd-meyer/ci-cd/.github/workflows/deploy-pages.yaml@main
    with:
      # Pass the specific environment name for this deployment
      # For now, we'll use 'github-pages' as our dev environment target
      environment-name: dev

  # Deploy to the target environment by calling a reusable workflow
  deploy-to-uat:
    name: Deploy to UAT environment
    if: |
      github.event_name == 'pull_request' && 
      startsWith(github.base_ref, 'test/')
    needs: build-app  # Depends on build application completion
    # Grant permissions to the reusable workflow
    permissions:
      pages: write
      id-token: write
    uses: jd-meyer/ci-cd/.github/workflows/deploy-pages.yaml@main
    with:
      # Pass the specific environment name for this deployment
      # For now, we'll use 'github-pages' as our dev environment target
      environment-name: uat

  # Deploy to the target environment by calling a reusable workflow
  deploy-to-prd:
    name: Deploy to PRD environment
    if: |
      github.event_name == 'pull_request' && 
      startsWith(github.base_ref, 'release/')
    needs: build-app  # Depends on build application completion
    # Grant permissions to the reusable workflow
    permissions:
      pages: write
      id-token: write
    uses: jd-meyer/ci-cd/.github/workflows/deploy-pages.yaml@main
    with:
      # Pass the specific environment name for this deployment
      # For now, we'll use 'github-pages' as our dev environment target
      environment-name: prd

  # Download and list my artifact.
  verify-artifact:
    name: Verify Artifact
    runs-on: ubuntu-latest
    needs: build-app  # Depends on build application completion
    steps:
      - name: download-artifact
        uses: actions/download-artifact@v4
        with:
          # required for Pages artifacts
          name: github-pages
      - name: List artifact contents
        run: ls -R
