# .github/workflows/sdlc.yaml
name: Hello World

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Use the local composite action you just created.
      # The path is relative to the root of your repository.
      - name: Checkout repository
        uses: ./.github/actions

      - name: Run a one line script
        run: echo "Hello World!"