# .github/workflows/sdlc.yaml
name: Hello World

on:
  push:
    branches:
      - main
    paths:
      # This path triggers the workflow for any change in the repository.
      # You might want to make this more specific, e.g., 'src/**'
      - '.'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # It's best practice to use a more specific version of actions
      # to avoid unexpected breaking changes.
      - uses: actions/checkout@v4                   # 1. Get the code to run
      - name: Set up node.js                        # 2. Set up the runtime environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies                  # 3. Install dependencies
        run: npm ci
      - name: Run HTMLHint                          # Run the HTML linter
        run: npx htmlhint ***/*.html"