# .github/workflows/sdlc.yaml
name: Hello World

on:
  push:
    branches:
      - main
    paths:
      # This path triggers the workflow for any change in the repository.
      # You might want to make this more specific, e.g., 'src/**'
      - '.'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # It's best practice to use a more specific version of actions
      # to avoid unexpected breaking changes.
      - uses: actions/checkout@v4
        run: echo Hello World!